house_ads_livewrapped_source_script_pid:
  default: ''
  type: string
  description:
    en:  "Enter the source script pid"
house_ads_livewrapped_source_tag_id_base_string_desktop:
  default: ''
  type: string
  description:
    en:  "Enter the tag id format, placing a # where the iteration number should be (desktop)"
house_ads_livewrapped_source_tag_id_base_string_mobile:
  default: ''
  type: string
  description:
    en:  "Enter the tag id format, placing a # where the iteration number should be (mobile)"
house_ads_livewrapped_always_start_at_op:
  default: true
  type: bool
  description:
    en: "Always start series immediately after first Post"
house_ads_livewrapped_always_at_last_post:
  default: true
  type: bool
  description:
    en: "Always place ad after last Post"
house_ads_livewrapped_tag_id_above_discovery_mobile:
  default: ''
  type: string
  description:
    en: "Enter the tag id for the ad above discovery (mobile)"
house_ads_livewrapped_tag_id_above_discovery_desktop:
  default: ''
  type: string
  description:
    en: "Enter the tag id for the ad above discovery (desktop)"
house_ads_livewrapped_tag_id_above_suggested_mobile:
  default: ''
  type: string
  description:
    en: "Enter the tag id for the ad above suggested (mobile)"
house_ads_livewrapped_tag_id_above_suggested_desktop:
  default: ''
  type: string
  description:
    en: "Enter the tag id for the ad above suggested (desktop)"
